//
// Generated file, do not edit! Created by nedtool 4.6 from src/stack/mac/packet/LteRac.msg.
//

#ifndef _LTERAC_M_H_
#define _LTERAC_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/stack/mac/packet/LteRac.msg:13</tt> by nedtool.
 * <pre>
 * packet LteRac
 * {
 *     // meaningful only for DL (response) RAC packets : if true RAC request has been admitted.
 *     bool success;
 * }
 * </pre>
 */
class LteRac : public ::cPacket
{
  protected:
    bool success_var;

  private:
    void copy(const LteRac& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRac&);

  public:
    LteRac(const char *name=NULL, int kind=0);
    LteRac(const LteRac& other);
    virtual ~LteRac();
    LteRac& operator=(const LteRac& other);
    virtual LteRac *dup() const {return new LteRac(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);
};

inline void doPacking(cCommBuffer *b, LteRac& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LteRac& obj) {obj.parsimUnpack(b);}


#endif // ifndef _LTERAC_M_H_

