//
// Generated file, do not edit! Created by nedtool 4.6 from src/common/timer/TMultiTimerMsg.msg.
//

#ifndef _TMULTITIMERMSG_M_H_
#define _TMULTITIMERMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "TTimerMsg_m.h"
// }}

/**
 * Class generated from <tt>src/common/timer/TMultiTimerMsg.msg:19</tt> by nedtool.
 * <pre>
 * packet TMultiTimerMsg extends TTimerMsg
 * {
 *     unsigned int event;
 * }
 * </pre>
 */
class TMultiTimerMsg : public ::TTimerMsg
{
  protected:
    unsigned int event_var;

  private:
    void copy(const TMultiTimerMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TMultiTimerMsg&);

  public:
    TMultiTimerMsg(const char *name=NULL, int kind=0);
    TMultiTimerMsg(const TMultiTimerMsg& other);
    virtual ~TMultiTimerMsg();
    TMultiTimerMsg& operator=(const TMultiTimerMsg& other);
    virtual TMultiTimerMsg *dup() const {return new TMultiTimerMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getEvent() const;
    virtual void setEvent(unsigned int event);
};

inline void doPacking(cCommBuffer *b, TMultiTimerMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TMultiTimerMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _TMULTITIMERMSG_M_H_

