//
// Generated file, do not edit! Created by nedtool 4.6 from src/common/timer/TTimerMsg.msg.
//

#ifndef _TTIMERMSG_M_H_
#define _TTIMERMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "LteCommon.h"
// }}

/**
 * Class generated from <tt>src/common/timer/TTimerMsg.msg:19</tt> by nedtool.
 * <pre>
 * packet TTimerMsg
 * {
 *     unsigned int timerId;
 *     unsigned short type @enum(TTimerType);
 * }
 * </pre>
 */
class TTimerMsg : public ::cPacket
{
  protected:
    unsigned int timerId_var;
    unsigned short type_var;

  private:
    void copy(const TTimerMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TTimerMsg&);

  public:
    TTimerMsg(const char *name=NULL, int kind=0);
    TTimerMsg(const TTimerMsg& other);
    virtual ~TTimerMsg();
    TTimerMsg& operator=(const TTimerMsg& other);
    virtual TTimerMsg *dup() const {return new TTimerMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getTimerId() const;
    virtual void setTimerId(unsigned int timerId);
    virtual unsigned short getType() const;
    virtual void setType(unsigned short type);
};

inline void doPacking(cCommBuffer *b, TTimerMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TTimerMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _TTIMERMSG_M_H_

